//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cdc.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public string ChildId { get; set; }
        public System.DateTime PaymentTime { get; set; }
        public decimal PaymentSum { get; set; }
    
        public virtual Child Child { get; set; }
    }
}
